#!/bin/sh

command=$2;

if [ $# -lt 2 ]
then
	echo "$0 servertype[_id] command";
	exit;
fi

dstfile=".dstfile.$RANDOM";

sh gen_dsthost.sh $1 $dstfile;

while read line
do
	host=`echo $line | awk '{print $1}'`;
	user=`echo $line | awk '{print $2}'`;
	passwd=`echo $line | awk '{print $3}'`;

	expect cmd.exp $user $host $passwd "$command";
done < $dstfile

rm $dstfile;
