#!/bin/bash

if [ $# -lt 1 ]
then
	echo "$0 servtype[_id]";
	exit;
fi

dstfile=".dstfile.$RANDOM";

sh gen_dsthost.sh $1 $dstfile

line=`head -n 1 $dstfile`;

host=`echo $line | awk '{print $1}'`;
user=`echo $line | awk '{print $2}'`;
passwd=`echo $line | awk '{print $3}'`;

rm $dstfile;

expect ssh.exp $user $host $passwd "$2" 
