#!/usr/bin/expect -f
set ipaddress 10.11.11.11
set port 22
set username aaa 
set passwd AAA 
set timeout 30
spawn ssh $ipaddress -p$port -l$username
expect {
"yes/no" { send "yes\r";exp_continue }
"password:" { send "$passwd\r" }
}
expect -re "(\$|>|#) "
interact 
