#!/bin/sh

srcpath=$2;
dstpath=$3;

if [ $# -lt 3 ]
then
	echo "$0 servertype[_id] srcpath dstpath";
	exit;
fi

dstfile=".dstfile.$RANDOM";

sh gen_dsthost.sh $1 $dstfile

while read line
do
	host=`echo $line | awk '{print $1}'`;
	user=`echo $line | awk '{print $2}'`;
	passwd=`echo $line | awk '{print $3}'`;

	echo $line;
	expect ldown.exp $user $host $passwd "$srcpath" "$dstpath" 
done < $dstfile

rm $dstfile;
